# Generated by Django 5.0 on 2024-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="UniqueId",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
