# Generated by Django 5.0 on 2024-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
